### ISSUE TITLE
Allow HTML tags in text to be rendered via Mustache

### ISSUE THREAD

**Issue by michael-franke** [babe-project/babe-project#11]
View templates should use triple braces {{{ VARIABLE }}} around elements to be inserted via Mustache. Else HTML tags will not be rendered but show up as text.

**Comment by stelaseldano** [comment]
Actually I removed Mustache since we are using ES6 and we can use [JS template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) now. It works the same way.

`cosnt text = "Here is the <a href='https://github.com/babe-project/MinimalTemplate'>Minimal Template</a>."`

in the template will be:
Here is the [Minimal Template](https://github.com/babe-project/MinimalTemplate)
